### ISSUE TITLE
Text Message Header | Protocol Layer

### ISSUE THREAD

**Issue by GrapesGoober** [GrapesGoober/RSA-App#13]
# Problem
For every message sent, there should be a message header telling the receiver some basic information, such as type, name, and size. The receiver should be able to read this header, determine what it's for, and even classify that the message received was in error. However, this protocol isn't designed yet. 

# To Do
- We need to design what should the protocol look like
- Think about sending & receiving
- Note that only type `bytes` can be sent over the channel, no other types possible. As such, the protocol must be powerful enough to handle file types

**Comment by GrapesGoober** [comment]
# Idea
This could be multiple packet protocol. Here's what I think of the sequence:
1. Sender says "I'm about to send XXX type of message, size of YY"
2. Receiver can "Accept" or "Deny"
3. Sender starts encrypting & sending, receiver starts printing onto screen (as it decrypts)
4. Receiver checks data, sends "OK" or "NOT OK"

**Comment by Noravorn2546** [comment]
On 3 idea: Why don't wait for all file to decrypts before print results?

**Comment by GrapesGoober** [comment]
Closed, as protocol would be concerned with block-based message instead
