### ISSUE TITLE
Basic Functionality | App Layer

### ISSUE THREAD

**Issue by GrapesGoober** [GrapesGoober/RSA-App#16]
# Problem
I think we should start doing basic minimum requirements for now. Essentially, basic UI, sending, receiving, encrypt and decrypt. The code mostly exists, we just have to put them together

# Solution
- Branch/Folder: `Development-App` and `main.py`
- Write basic UI functionality for
- [x] `config.json` file to read & write. Retrieve required info.
- [ ] Key Generation UI
- [x] Key Input UI
- [x] IP input UI
- [x] Port Input UI
- [ ] Chat Room UI
 
The idea is that the user should be able to select what they wanna do (Oh, i wanna generate a new key. Oh, i wanna send some messages. Oh, I wanna change the IP addresses) solely via command line.

# Note
Keep in mind that App Layer is concerned solely with the user interface and handling inputs/outputs. This layer does not handle the protocol for sending, the UDP sockets, nor encryption

**Comment by GrapesGoober** [comment]
# Design
You might have to design an interface for doing this. One idea is (instead of command line) is to use a config json file so that user can set up what kinds of info they need.

**Comment by Noravorn2546** [comment]
I create some basic UI for the program and code to change data in JSON but I still does not add function to send message and generate key.

**Comment by Noravorn2546** [comment]
I create it in new file. You might need to relocate them to main when finalize.

**Comment by GrapesGoober** [comment]
# My Thoughts
I've taken a look at your code and i've got some feedback. This code is good for now for this issue, so I'd close it. For some additional changes, I'll post you a new issue
