### ISSUE TITLE
Key Exchange | Protocol Layer

### ISSUE THREAD

**Issue by GrapesGoober** [GrapesGoober/RSA-App#19]
# Problem
Currently, the chatroom server and clients does not handle any RSA security measures. Let's get to work designing and implementing this feature
# Design
- The server chatroom only keeps public keys for syncing
- `CHAT` clients would need a public key-sync from server upon key updates
- `CHAT` clients will have to send its own user's public keys upon connection. Failure will terminate conn.
- `SYNC` clients only need private keys as local variable (say, as argument). 
- If user wish to change keys, they have to terminate the `SYNC` and `SYNC` client. This is to prevent race conditions. The keys must be exchanged to server properly before transmission

**Comment by GrapesGoober** [comment]
# Ideas
- How about save different user types in a separate list/dict? So that you don’t need to have dedicated type fields for each user. This also makes checking much simpler.
- Chat type only needs to declare public keys and names

**Comment by GrapesGoober** [comment]
# Ideas For Key Exchange
- Print key integer (not in bytes, no, in ASCII integer), so that the user can copy pasted into config or terminal
- Another client module to sync keys specifically
- `CHAT` clients will block until the other `CHAT` client joins, at which point they can share keys. Note that the public keys are only needed for `CHAT` clients. Private keys are already generated in the config file

**Comment by GrapesGoober** [comment]
# Let's Not Do Chatroom?
The problem is that chatroom app has a unique problem with messages. This seems like an absolute mess. We should do a direct 1-1 chat instead, no central chatroom.
- Note that there would still be a "server" and a "client" still
- There should still be a separate class/func/thread/process handling chat & sync

**Comment by Noravorn2546** [comment]
Idea for chat

- let the user take turn to send messages
- make the user need to recieve message from the another user before be able to send another message

**Comment by GrapesGoober** [comment]
# Continue to file transfer app
Turns out that the main difficulty to the key exchange problem is not the keys themselves, but the architecture of the chatroom. Doing file transfer seems so much simpler
