### ISSUE TITLE
Problem with UI for file tranfer

### ISSUE THREAD

**Issue by Noravorn2546** [GrapesGoober/RSA-App#21]
### Question

1. Where to insert a file and how to store them
2. How to received keys before enter function `(receive_stream)`

**Comment by GrapesGoober** [comment]
# Idea
The idea I have now is this:
- The receiver must already have the keys (this could be stored in config file or asked to recompute the keys)
- The receiver must already have an empty destination file to receive the data
- The receiver must have the app running in receive mode
- The sender must already have a file stored on disk. This could be any file (txt, zip, anything)
- The sender must know the IP and PORT of the receiver
- The sender then run the app with (at least) these inputs
  - IP
  - PORT
  - path to file
- The app will exchange keys and start sending the data

# Unsure Issues
- For receiver, it's ok to have the app store the keys beforehand. Maybe have a UI option for user to recompute the keys if they want to
- For receiver, maybe have the app create a new file to store data? Maybe it's better than using existing file. Maybe put this new file in a dedicated folder?
- For sender, maybe have the app also send the file name? This might be useful for receiver to receivev the appw

**Comment by GrapesGoober** [comment]
# App Protocol
Here, I wanna talk about how the protocol works. Note that technically I should be writing a full documentation for you, but I think a comment should be fine. If you don't understand something, just ask it in the comments
## `receive_stream(ip: str, port: int, keys: tuple[int, int])`
Arguments:
- `ip: str`
- `port: int`
- `keys: tuple[int, int]` This is for the private key.
Returns: `Generator[bytes, None, None]` a iterable generator for each block of data received. To read from this iterable, put it into a `for` loop.
This function sets up a receiving server at host `ip` and `port`. It awaits for a potential sender to connect. After a sender has connected, it will send its keys to sender, then the sender can transmit.
### Note
- This function will block further code execution until the a sender connects to server. At which point, the function returns an iterable generator
- This function only takes private keys, which might strike as a little odd. Here's why
  - The public key only contains `(e, n)` while private key only contains `(d, n)`
  - The "encrypt" exponent "`e`" is a fixed constant `65537` hardcoded into protocol
  - The "modulus" component "`n`" is same for both keys. This number is computed by the receiver
  - Technically, the modulus is the only number to exchange with the sender. The encrypt exponent is not needed as everybody could just assume it's a fixed constant `65537`
  - I may need to change the `RSA.generate_keys` function to return just `(d,n)` as opposed to `(e,n),(d,n)` to simplify this further
  -

**Comment by GrapesGoober** [comment]
# Update
I've updated the previous comment on the function documentation. They do (mostly) the same things, but I made them hella lot more readable.

**Comment by GrapesGoober** [comment]
# Idea: Args Input
I'm not sure if this would be helpful for you, but I notice you have difficulties with handling inputs. Maybe use arguments instead of individual inputs? There's an `argparse` library that makes this easier, you might wanna check that out. Anyways, it's just a suggestion.

**Comment by GrapesGoober** [comment]
Need an update on your progress

**Comment by Noravorn2546** [comment]
Complete
