### ISSUE TITLE
Brief on Git workflow

### ISSUE THREAD

**Issue by GrapesGoober** [GrapesGoober/RSA-App#4]
# Problem
I'm not sure if Neo is familiar with Git workflow. I think it's gunna be great if we can meet either online or onsite to brief about this, it'd be really effective. 

# Solution?
On Sunday 1pm, Need to talk about
- [x] branches: what we have now, what they mean, how they work
- [x] commits: how to write code, make commits, and sync
- [x] pull requests: how I get to check code, how to quality check
- [x] vscode: need to brief all of this from the vscode perspective

**Comment by GrapesGoober** [comment]
# What day?
What day shall we do this? Online or onsite is fine. Also, I'd be nice if we can use a real issue to demonstrate the workflow

**Comment by Noravorn2546** [comment]
อาทิตย์นี้ก็ได้ ว่างอยู่

**Comment by GrapesGoober** [comment]
ok, 10 am or 1 pm? This shouldn't take long, I'd guess 30 minutes probably.

**Comment by Noravorn2546** [comment]
บ่ายโมงก็ได้

**Comment by GrapesGoober** [comment]
OK, sunday 1 pm

**Comment by GrapesGoober** [comment]
Finished
